services:
  goldprice.web:
    build:
      context: .
      dockerfile: GoldPrice.Web/Dockerfile
    ports:
      - "8333:8080"
    volumes:
      - ./data:/app/data:rw,Z
    environment:
      - ASPNETCORE_ENVIRONMENT=Production